## 파이선 리스트
: 가변형, 시퀀스(str, list, tuple)=[+, *(반복연산자), 중첩, 슬라이싱, 인덱싱][]
    - 단점 : 동작 속도가 느리다. 콤마로 요소 분리, 구별

### numpy : 수식 라이브러리, 수칙연산, 배열객체

    - 동작 속도가 빠르다 ./연속적인 메모리/한가지 타입만 처리가능
    - 행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리

1)np.array로 객체 생성 \
2)np.arange로 객체 생성

In [2]:
#ndarry(shape[,dtype, buffer, offset,...])

import numpy as np



In [3]:
a = np.array([0,1,2,3,4,5]) #=ndarray

In [4]:
print(a)#출력확인 ',' 없음
print(type(a))
print(a.dtype)#a 객체가 가진 데이터 타입

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [5]:
print(dir(np.sctypeDict))
np.sctypeDict.keys() #numpy에서 사용되는 데이터 타입

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'b1', 'int64', 'i8', 'uint64', 'u8', 'float16', 'f2', 'float32', 'f4', 'float64', 'f8', 'complex64', 'c8', 'complex128', 'c16', 'object0', 'bytes0', 'str0', 'void0', 'datetime64', 'M8', 'timedelta64', 'm8', 'Bytes0', 'Datetime64', 'Str0', 'Uint64', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_', 'int', 'float', 'complex', 'bool', 'ob

In [6]:
a = np.array([0.0,1.0,2.0,3.0,4.0,5.0]) # 출력 확인 ','가 없음!
print(a)
print(type(a))
print(a.dtype)#a 객체가 가진 데이터 타입 / 0,1 = bit * 8 =1byte=주소생성(-128~127)
#주소 생성 -> 메모리 할당 -> 값 대입


#불리언 bool(1), byte(1)
#정수형 short(2) -> int32(4)->int64(8) -> long(8)~(16)
#실수형 floot(4) ='float32','f4'->float(8)->double(8)
#문자와 문자열 -> str

#ex) int32 = 정수형 32bit , i4 = 정수형 4byte ,
# float64= f8 =실수형 64bit =실수형 8byte


[0. 1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [7]:
a = np.arange(10 )#0~9 #,로 구분하지 않는다.
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [8]:
a=[1,2,3,4,5]# numpy 아닐 떄는 ',' 출력
a

[1, 2, 3, 4, 5]

3) ndarry(shape[,dtype, buffer, offset,...])----> shape 관련\
3-1: 차원 (Rank, Dimension)을 []로 갯수로 늘린다.[[[]]]
[[[a]]] 3차원 [[b ]]2차원\
아벨 선생이 4차원 이상은 사람이 연산 못해 -> 컴퓨터
대상 -> 특징 추출 (x_독립변수, y_종속변수(정답라벨))\
3-2 차원의 종류\
    1차원 shape(x,)\
    2차원 shape(x,y), 행렬(matrix)\
    3차원 shape(x,y,z), (행, 렬, 면 ) ->(면, 행, 렬) 변환작업필요\
    ...n차원 : (x,y,z,,,,,,)\

In [9]:
# 1차원 shape(x, )
a=np.arange(12)
print(a)
print(a.shape) # (12, ) -> 1차원이야
t=a.shape
print(type(t))
print((a.shape)[0])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
<class 'tuple'>
12


In [10]:
#2차원 배열의 shape : 행(row, 수직(이미지연산), axis=0)과 열(column, 수평(이미지연산) axis=1)
m=np.array([[0,1,2],
            [0,1,2]])
print(m)
print(m.shape) 
print(m.shape[0],m.shape[1])

[[0 1 2]
 [0 1 2]]
(2, 3)
2 3


In [11]:
#3차원 배열의 shape :(면,행,열) 2행 3열이 2면이 있는 행열
m=np.array([[
            [0,1,2],
            [3,4,5]],
            [[0,1,2],
            [3,4,5]]])
print(m)
print(m.shape) 
print(m.shape[0],m.shape[1],m.shape[2])

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)
2 2 3


4)배열과 슬라이싱 _reshape()

In [12]:
#2차원 배열 인덱싱 슬라이싱
a=np.arange(12).reshape(3,4) #0~11(12)까지의 수를 3행 4열로 만들어라
print(a)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [13]:
#a가 가진 값 0,0,9를 리턴해보자 = index로 접근

print(a[0][0])
print(a[0,0])
print(a[2][1])
print(a[2][3],a[2,3])

0
0
9
11 11


In [15]:
#a가 가진 슬라이싱
#[ 0  1  2  3]
print(a)
print()
print(a[0])
print()
print(a[0, :]) # #[행, 열] a[start, end]
print()
print(a[:,:-1])#행은 모두,, 열은 마지막 열을 제외하겠다
print()
print(a[:,1:])#첫번쨰 열을 제외하겠다
print()
print('슬라이싱으로 전체 출력 형식을 만들자.')
print(a[:,:])
print()
print(a[0:,0:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3]

[0 1 2 3]

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

슬라이싱으로 전체 출력 형식을 만들자.
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
#0행의 모든 데이터를 20으로 변경 후 전체 출력 해보자.
a[0]=20
print()
print(a[:,:])
print()
print(a[::2,::2])#[start:end-1:step] step 행 열이 step만큼 옮겨감


[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[20 20]
 [ 8 10]]


In [19]:
#슬라이싱 요소 전체의 값을 변경해보자.
print(a[:,:])
print()
print(a[::2, ::3])
print()
a[::2, ::3]=0 #꼭짓점에 0
print(a[:,:])
print()
a[:,:]=-1
print(a[:,:])

[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[20 20]
 [ 8 11]]

[[ 0 20 20  0]
 [ 4  5  6  7]
 [ 0  9 10  0]]

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [50]:
#3차원 배열 인덱싱 슬라이싱
a=np.arange(12).reshape(2,2,3)
print(a, a.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [52]:
#인덱싱
print(a[0][0][0])
print(a[0,0,0])

#5
print(a[0,1,2])

0
0
5


In [69]:
#슬라이싱
print(a[ :, :, : ])#전체출력
print()
print(a[ :,1 :, 1: ])
print()
#case1 :
#6 7
print(a[ 1:,   :-1 ,  :2 ])
#4 5
print(a[ :-1,1 :,1 : ])

#case2:
#6 7
print(a[ 1,  0 ,  :2 ])
#4 5
print(a[ 0,1,1: ])

#case3:
print(a[1:,:1,:2])
print(a[:1,1:,1:])

#case4:
print(a[1,:-1,:-1], a[0,1:,1:])

#6 7
print(a[ 1,  0 ,  :-1 ])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

[[[ 4  5]]

 [[10 11]]]

[[[6 7]]]
[[[4 5]]]
[6 7]
[4 5]
[[[6 7]]]
[[[4 5]]]
[[6 7]] [[4 5]]
[6 7]


5) ☆★불린인덱싱 : 조건식을 이용한 인덱싱, 조건 검색 필터를 사용한 추출값☆★

In [21]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [22]:
print(a>2)
#배열의 객체 a에서 2보다 큰 값을 배열로 리턴
print(a[a>2]) # 이미지 -> 빨간사과 -> 이상값(노이즈) 추출해서 변경하고 싶다.

[False False  True  True  True  True]
[3 4 5 6]


In [23]:
bool_index=np.array([True, False, True, True, True, True])
print(bool_index)
print(a[bool_index])

[ True False  True  True  True  True]
[1 3 4 5 6]


In [24]:
#배열 a에서 3이 아닌 요소를 추출
print(a[a!=3])



#2보다 크고 6보다 작은 요소를 추출
# ***&&가 아니라 &*** 주의 
print(a[(a>2) & (6>a)])

#짝수만 추출
print(a[a%2==0])

#평균보다 작은 값을 추출해보자.
#평균 계산 함수 mean() ,, avr(a) ->sql문과 헷갈리지 말기
print(a[a<a.mean()],a.mean())

[1 2 4 5 6]
[3 4 5]
[2 4 6]
[1 2 3] 3.5


6) 배열의 형상 다루기 : reshape(), flatten()(편평화), transpose()(전치)

In [35]:
#flatten(): 다차원 배열을 1차원으로 만든다.
a=np.arange(12).reshape(3,4)
print(a,a.shape)

f=a.flatten() #(3,4)---->(12,)
print(f,f.shape)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


In [28]:
#데이터 순서를 거꾸로 변경
#----------a[행:렬:step]-------------#
print(a[: : -1])#행의 순서를 거꾸로 변경
print()
print(a[:, : : -1])#열의 순서를 거꾸로 변경
print()
print(a[::-1, ::-1]) #행과 열의 순서를 거꾸로 변경
print()
print('-'*20)

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]

--------------------


In [29]:
# transpose() : 전치행렬, 행과 열을 서로 맞바꾸는 함수
t=a.transpose()
print(t, t.shape) # (3,4)---->(4,3), (x,y)---->(y,x)
print(a.T) #transpose() 함수와 동일한 결과

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] (4, 3)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [30]:
#print(help(dir(a.T)))

a.flat=0# 임시로 1차원으로 변경 후 값을 0으로 대입받고 차원을 다시 리턴한다.
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


6) numpy의 속성(Attribute) : 멤버변수, 메서드
dtype, shape, ndim, flat, T, size, nbytes

In [36]:
d = np.arange(12).reshape(3,4)
print(d,d.shape)
print(d.dtype)  # int32 or int64
print(d.ndim)   # 2차원  ==> print(len(d.shape)) 와 동일
print(d.T)      # transpose()함수와 동일한 결과, 전치행렬
print(d.size)   # 12개 , 요소의 갯수
print(d.nbytes) # 48 bytes : 32bit(4 byte) * 12 
d.flat = 1
print(d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
int32
2
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
12
48
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [45]:
#numpy 통계 함수들
a = np.arange(12).reshape(3,4)
print(a,a.shape)

print(a.max(), np.max(a))#최대값
print()
print(a.min(),np.min(a)) #최소값
print()

print(a.sum())#합
print(a.mean())#평균

print(a.std())#표준편차
print(a.var())#분산
print(np.median(a))#중위수


#사분위 수
print('25%:', np.percentile(a,25)) #1사분위수(Q1)
print('50%:', np.percentile(a,50))#2사분위수(Q1), median()과 같은 값
print('75%:', np.percentile(a,75)) #13사분위수(Q3)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
11 11

0 0

66
5.5
3.452052529534663
11.916666666666666
5.5
25%: 2.75
50%: 5.5
75%: 8.25


In [44]:
dir(np) # median 오타로 오류가 나서 np내의 객체를 확인해봄

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
